config/routes.rb
Rails.application.routes.draw do

  resources :usuarios

  get 'login' => 'session#login', as: 'login'
  get 'callback' => 'session#callback', as: 'callback'
  get 'logout' => 'session#destroy', as: 'logout'

  root 'session#login'

end

app/models/tipo_vinculo.rb
class TipoVinculo < ActiveRecord::Base
    belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :tipo_vinculos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper

end

app/controllers/session_controller.rb
class SessionController < ApplicationController


  def login

    # Parte conceitual: http://oauthbible.com/
    # A USP usa o OAuth 1.0a (Three Legged)

    # 1. Gera objeto consumidor
    @consumer = gera_consumidor

    # 2. Faz a primeira requisição, pegando request token/secret, que serão futuramente trocados por um access_token/secret
    @request_token = @consumer.get_request_token

    # 3. Salva o par de request token/secret gerados na sessão, pois serão usados na troca
    session[:token] = @request_token.token
    session[:token_secret] = @request_token.secret

    session[:usuario_id] = nil

    # 4. Envia usuário para URL de autorização
    redirect_to @request_token.authorize_url + @callback_id

  end

  def callback

    # 5. Gera um objeto consumidor - na verdade não precisaria, poderia usar o mesmo, but sorry, I do not know Ruby...
    @consumer = gera_consumidor

    # 6. Gera um hash (tipo um dicionário em python com chave/valor) com os requests token que estão na sessão (passo 3)
    hash = { oauth_token: session[:token], oauth_token_secret: session[:token_secret]}

    # 7. Constrói o objeto @request_token para fazermos a troca
    @request_token  = OAuth::RequestToken.from_hash(@consumer, hash)

    # 8. Requisita o access token, passando oauth_verifier retornado via get (Three Legged)
    @access_token = @request_token.get_access_token(oauth_verifier: params[:oauth_verifier])

    # 9. Com posse do access token, faça uma requisição POST
    json_response = @access_token.post("https://uspdigital.usp.br/wsusuario/oauth/usuariousp")
    @data = JSON.parse(json_response.body)

    # 10. Com os dados, seja feliz!! (e claro, salve os dados localmente, faça login do fulano(a), etc etc)
    print @data

    loginUsuario = tratauser

    log_in loginUsuario

  end

  def tratauser

      loginUsuario = @data["loginUsuario"]

      userexiste = Usuario.where(:loginUsuario => loginUsuario)

      if userexiste.empty?
        user = Usuario.new
      else
        user = Usuario.find_by_loginUsuario(loginUsuario)
      end

      user.loginUsuario = loginUsuario
      user.nomeUsuario = @data["nomeUsuario"]
      user.tipoUsuario = @data["tipoUsuario"]
      user.emailPrincipalUsuario = @data["emailPrincipalUsuario"]
      user.emailAlternativoUsuario = @data["emailAlternativoUsuario"]
      user.emailUspUsuario = @data["emailUspUsuario"]
      user.numeroTelefoneFormatado = @data["numeroTelefoneFormatado"]
      user.ramalUsp = @data["ramalUsp"]

      user.save

      id = user.id

      @vinculo = @data["vinculo"]

      @vinculo.each do |v|

        vinculoexiste = TipoVinculo.where(:usuario_id => id, :tipoVinculo => v["tipoVinculo"])

        if vinculoexiste.empty?
          tipoVinc = TipoVinculo.new
        else
          tipoVinc = TipoVinculo.find_by(:usuario_id => id, :tipoVinculo => v["tipoVinculo"] )
        end

          tipoVinc.codigoSetor = v["codigoSetor"]
          tipoVinc.nomeAbreviadSetor = v["nomeAbreviadSetor"]
          tipoVinc.nomeSetor = v["nomeSetor"]
          tipoVinc.codigoUnidade = v["codigoUnidade"]
          tipoVinc.siglaUnidade = v["siglaUnidade"]
          tipoVinc.nomeUnidade = v["nomeUnidade"]
          tipoVinc.nomeVinculo = v["nomeVinculo"]
          tipoVinc.nomeAbreviadoFuncao = v["nomeAbreviadoFuncao"]
          tipoVinc.tipoVinculo = v["tipoVinculo"]
          tipoVinc.usuario_id = id

          tipoVinc.save!

      end

      return loginUsuario

  end


  def gera_consumidor

    @callback_id = ENV['CALLBACK_ID']
    key = ENV['ICB_OAUTH']
    secret = ENV['SECRET_OAUTH']

    return OAuth::Consumer.new(key, secret, {
                                      :site               => "https://uspdigital.usp.br",
                                      :scheme             => :header,
                                      :http_method        => :post,
                                      :request_token_path => "/wsusuario/oauth/request_token",
                                      :access_token_path  => "/wsusuario/oauth/access_token",
                                      :authorize_path     => "/wsusuario/oauth/authorize"
                                  })
  end





  def destroy
    log_out
    redirect_to login_path
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:destroy, :edit, :update]


  def index
    @usuarios = Usuario.all
  end

  def destroy

    @tipovinculo = TipoVinculo.where(:id => @usuario.id)

    @tipovinculo.destroy_all

    @usuario.destroy!

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuarios_url, notice: 'Usuário alterado com sucesso.' }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def usuario_params
    params.require(:usuario).permit(:loginUsuario, :nomeUsuario, :tipoUsuario, :emailPrincipalUsuario, :emailAlternativoUsuario, :emailUspUsuario, :numeroTelefoneFormatado, :ramalUsp)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/session_helper.rb
module SessionHelper

  #cria uma sessão
  def log_in(loginUsuario)
    session[:usuario_id] = loginUsuario
  end

  #destroi a sessão criada na def anterior
  def log_out
    session.destroy
    @current_user = nil
  end

  #busca um usuário cuja sessão não seja nula (ou seja, tem uma sessão marcada pelo laboratorio.id)
  def current_user
    @current_user ||= Usuario.find_by(loginUsuario: session[:usuario_id])
  end


end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Senhaunica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">

    <ul class="nav navbar-nav">
      <% if session[:usuario_id] != nil %>
          <li class="lead"> <%= link_to "Usuários", usuarios_path %></li>

      <% end %>

      <li class="lead"> <%= link_to "Sair" , logout_path %></li>

    </ul>
  </div>
</nav>

<p>Você está logado com o usuário: <b><%= session[:usuario_id] %></b> </p>

<%= yield %>


</body>
</html>

app/views/session/callback.html.erb
<h1>Login feito com sucesso!</h1>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
    <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

          <ul>
            <% @usuario.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :loginUsuario, "Login" %><br>
      <%= f.text_field :loginUsuario %>
    </div>

    <div class="field">
      <%= f.label :nomeUsuario, "Nome" %><br>
      <%= f.text_field :nomeUsuario %>
    </div>

    <div class="field">
      <%= f.label :tipoUsuario, "Tipo do usuario" %><br>
      <%= f.text_field :tipoUsuario %>
    </div>

    <div class="field">
      <%= f.label :emailPrincipalUsuario, "E-mail principal do usuario" %><br>
      <%= f.text_field :emailPrincipalUsuario %>
    </div>

    <div class="field">
      <%= f.label :emailAlternativoUsuario, "E-mail alternativo do usuario" %><br>
      <%= f.text_field :emailAlternativoUsuario %>
    </div>

    <div class="field">
      <%= f.label :emailUspUsuario, "E-mail USP" %><br>
      <%= f.text_field :emailUspUsuario %>
    </div>

    <div class="field">
      <%= f.label :numeroTelefoneFormatado, "Telefone" %><br>
      <%= f.text_field :numeroTelefoneFormatado %>
    </div>

    <div class="field">
      <%= f.label :ramalUsp, "Ramal" %><br>
      <%= f.text_field :ramalUsp %>
    </div>

    <div class="actions">
      <%= f.submit "Salvar" %>
    </div>
<% end %>

app/views/usuarios/callback.html.erb
<h1>Dados retornados USP</h1>

<pre>
<%= @data %>
</pre>

app/views/usuarios/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form' %>


<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Lista de Usuários</h1>

<% @usuarios.each do |usuario| %>

    <table border="1">
        <thead>
            <tr>
                <th>Login</th>
                <th>Nome </th>
                <th>Tipo </th>
                <th>E-mail Principal</th>
                <th>E-mail Alternativo</th>
                <th>E-mail USP</th>
                <th>Telefone</th>
                <th>Ramal</th>
                <th colspan="2"></th>
            </tr>
        </thead>

        <tbody>
        <tr>
            <td><%= usuario.loginUsuario %></td>
            <td><%= usuario.nomeUsuario %></td>
            <td><%= usuario.tipoUsuario %></td>
            <td><%= usuario.emailPrincipalUsuario %></td>
            <td><%= usuario.emailAlternativoUsuario %></td>
            <td><%= usuario.emailUspUsuario %></td>
            <td><%= usuario.numeroTelefoneFormatado %></td>
            <td><%= usuario.ramalUsp %></td>
            <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
            <td><%= link_to 'Apagar', usuario, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        </tr>
        </tbody>
    </table>

    <table border="1">
        <thead>
            <tr>
                <th>Vinculo</th>
                <th>Nome do vinculo</th>
                <th>Sigla da unidade</th>
                <th>Nome da unidade</th>
                <th>Codigo do setor</th>
                <th>Nome do setor</th>
                <th>Nome da função</th>
            </tr>
        </thead>

        <tbody>
            <% @tipovinculo = TipoVinculo.where(usuario_id: usuario.id) %>

            <% @tipovinculo.each do |v| %>

                <tr>
                    <td><%= v.tipoVinculo %></td>
                    <td><%= v.nomeVinculo %></td>
                    <td><%= v.siglaUnidade %></td>
                    <td><%= v.nomeUnidade %></td>
                    <td><%= v.codigoSetor %></td>
                    <td><%= v.nomeSetor %></td>
                    <td><%= v.nomeAbreviadoFuncao %></td>
                </tr>
            <% end %>

        </tbody>
    </table>

    <br>

<% end %>

<br>

app/views/usuarios/login.html.erb
OK!

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>